version: "3.9"
services: 
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mahanta
      - POSTGRES_DB=tracking_inventory
  api: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment: 
      - DB_SOURCE=postgresql://root:mahanta@postgres:5432/tracking_inventory?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]

