// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Inventory struct {
	ID           int64     `json:"id"`
	Item         string    `json:"item"`
	SerialNumber string    `json:"serial_number"`
	Price        int64     `json:"price"`
	Owner        int64     `json:"owner"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Name              string    `json:"name"`
	Email             string    `json:"email"`
	Password          string    `json:"password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
